discsim/frank

.circleci/config.yml
docs/Makefile
docs/conf.py
docs/index.rst
requirements.txt

Following this tutorial:
https://circleci.com/blog/automate-your-nuxt-js-app-deployment/

Automatically build and deploy documentation

---

docs/conf.py
docs/index.rst
docs/py_API.rst
requirements.txt

The docs/py_API.rst file shows how to refer to Python objects/functions with urls and how to generate their documentation from the docstring.
@jeffjennings @rbooth200 pls have a look at the file, so you can write the docs you want.

Generate Python object docs from docstrings and add version number on homepage

---

frankenstein/hankel.py
frankenstein/radial_fitters.py
frankenstein/tests.py

Since a fit can be performed with, e.g., `FrankFitter` without first having to convert inc and PA from the user-provided unit [deg], the same should be true for `Rmax`. The user provides it in [arcsec], while it's handled internally in [rad]. But currently this conversion has to be done externally.
So in `hankel.py`, I've kept `self._Rnk` and `self._Rmax` in [rad], and just converted `Rmax` (not `self._Rmax`) to from [deg] to [rad] in `__init__`. This allows `Rmax` to be passed into `DiscreteHankelTransform` from `FourierBesselFitter` in the user-provided [arcsec], while still effectively handling `Rmax` internally in [rad] (consistent with `self._Rnk_`). 
In `tests.py` I've confirmed this change hasn't affected the fit by successfully running `test_frank_fitter()`. I've updated all …

Change internal unit of rmax to arcsec

---

frankenstein/geometry.py
frankenstein/radial_fitters.py

Fixes a bug in the following code:
```
fitter = FrankFitter(Rmax, N, FitGeometryGaussian())
sol1 = fitter.fit(u1,v1,vis1, w1)
sol2 = fitter.fit(u2,v2,vis2, w2)
```
Previously the second fit would change the geometry parameters of the sol1 fit, which is not the desired behaviour. This PR fixes that issue

Store geometry

---

frank/geometry.py
frank/io.py
frank/radial_fitters.py

In `geometry.deproject`, the ordering of the code needs to be amended as detailed in #93, and the return in `geometery.SourceGeometry.undo_correction` needs to be amended as detailed in #93, to correctly reproject the u,v coordinates and phase-unshift the visibilities. This PR makes these changes (verified as correct with multiple datasets). 
This PR also:
(1) updates the syntax in a few places in `geometry.py` so that it's consistent between functions, and so that function docstrings match the input and output variables.
(2) updates `radial_fitters._HankelRegressor.predict` to add the option to return the reprojected u and v in addition to the corresponding V. The default (and existing) behavior is just to return V, consistent with the `return` in `predict_deprojected`.
(3) following …

Fix reprojection bug

---

frank/io.py

This PR fixes #86, allowing frank to read zipped .txt and .dat (.txt.gz, .txt.bz2) formats

Added zipped file support

---

frank/default_parameters.json

this is why I always leave the house twice...
Changes `default_parameters.json` --> `hyperpriors: max_iter` from 1500 to 2000 to be consistent with #99

update default max_iter

---

docs/_static/custom.css
docs/conf.py

Fixed hiding of prompt in nbsphinx

---

setup.py

I've added the requirement of python >= 3 to setup.py. There is no good reason to support / allow python 2 since it is now no longer receiving security updates.
Closes #111

Added python 3 requirement

---

docs/index.rst
docs/install.rst

This PR mentions explicitly in the docs main page that frank requires Python >= 3.0.

Add note to docs on python3 requirement

---

frank/__init__.py
setup.py

Without these lines `import frank` doesn't do anything useful. Since the code is small I don't see a reason not to import the core library at least.
I had to update setup.py to prevent from importing the submodules and hitting problems with the dependencies.

Exposed sub modules

---

README.md

Somehow the logo got dropped (again) several commits ago...this just adds it back to the README.

Add logo back to readme

---

docs/py_API.rst
docs/quickstart.rst
docs/tutorials/fit_convergence.rst
docs/tutorials/fitting_mock_data.rst
docs/tutorials/fitting_procedure.ipynb
docs/tutorials/model_limitations.rst
docs/tutorials/prior_sensitivity.rst
frank/radial_fitters.py
frank/utilities.py

This PR fixes a few typos in the docs, updates dead hyperlinks in the docs, and fixes the last of the `WARNING`s one gets when building the docs (`make html`).

Update docs typos, minor rephrasing, fix dead links

---

frank/utilities.py

This PR fixes a bug I found in `estimate_weights`. 
The shape of the index arrays returned by argwhere is (\*, 1) rather than just (*) which needed fixing.

fixed bug in weights estimation

---

docs/quickstart.rst
frank/io.py

Clarify UVTable column formats based on file extension

---

frank/utilities.py

This PR makes `UVDataBinner` consistent with `utilities.estimate_weights`, which allows the option for `V` to only be real. Because `estimate_weights` calls `UVDataBinner`, the latter should then be able to handle a supplied `V` with only real components.

Allow UVDataBinner to intake and bin only real component of vis

---

frank/geometry.py
frank/tests.py

PR fixes a bug in which `guess` in `geometry/FitGeometryGaussian` becomes `NoneType` if `guess` is provided by user; PR also adds a test for `FitGeometryGaussian` when `guess` is provided

FitGeometryGaussian: 'guess' bug

---

README.md

PR adds persistent link for papers that cite frank to the README (this link is already in the docs).

Readme - add link to pubs citing frank

---

frank/fit.py

`fit.py` wasn't checking whether `norm_wle` was provided in the parameter file in the conditional for whether to call `alter_data`. And it wouldn't be obvious to a user from the logging that this correction hasn't been applied.

fit.py: include call to alter_data if norm_wle is provided

---

frank/plot.py

This PR prevents a warning that was arising when plotting data from a `UVDataBinner` object,
```
python3.7/site-packages/numpy/core/_asarray.py:85: UserWarning: Warning: converting a masked element to nan.
return array(a, dtype, copy=False, order=order)
```
We now check if the quantities being plotted are masked arrays, and if the masked values are `--` (as they are when using `np.ma.masked_where`). If so, new variables with those values converted to NaN are plotted.

Prevent MaskedArray warning in plot_vis_quantity

---

frank/default_parameters.json
frank/fit.py
frank/parameter_descriptions.json
frank/utilities.py

This PR:
- Adds a parameter to the `default_parameters.json` to set the `use_median` flag in the call to `estimate_weights` in `fit.py`
- Sets the default in the `.json` to `false`, i.e., don't set all estimated weights as the single median variance across bins. I've found using the alternative, the baseline-dependent variance, to give a more sensible result for both the binned visibilities (by comparing 1 and 50 k\lambda binned Re(V)) and the corresponding frank fit for some datasets.
- Changes `np.median` to `np.ma.median` in `estimate_weights` to avoid a `MaskedArray` warning:
```
python3.7/site-packages/numpy/core/fromnumeric.py:746: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
a.partition(kth, axis=axis, kind=kind, order=order)
```
I've verified this …

estimate_weights flexibility

---

frank/make_figs.py

Very minor change in `make_quick_fig` to ensure fit line plots in front of binned visibilities

quick_fig: ensure frank fit plots in front of data

---

frank/radial_fitters.py

A few people now have run into this error message when calling `FrankFitter`,
```
RuntimeWarning: overflow encountered in exp
pi_new = np.exp(sparse_solve(Tij_pI, beta + np.log(pi)))
ValueError: Bad value in power spectrum. The power spectrum must be postive and not contain any NaN values
```
In all cases (including my own experience), this has been due to one of: 
- the UVtable passing in `u` and `v` in [m] rather than [\lambda],
- the UVtable weights being incorrect (due to some aspect of extracting the UVtable from CASA), 
- the geometry/phase center used for the deprojection being pretty wrong, 
- or more rarely the fit's `rout` and/or `n` needing to be increased.
This PR just makes the above error message more verbose to help point people to these likely underlying causes.

more verbose _HankelRegressor overflow error message

---

docs/tutorials/fitting_procedure.ipynb
frank/geometry.py
frank/parameter_descriptions.json

Specify PA, dRA sign conventions

---

frank/make_figs.py
frank/plot.py

Fixes minor bug that applied wrong scaling to colorbars in `make_quick_fig`, `make_full_fig`

correct colorscale for 2d sweeps in figures

---

frank/radial_fitters.py
frank/tests.py

Fixes #172 and adds a regression test.
This needs to be propagated into the log normal model etc, which will be done after this PR is merged

Fix for predicting visibilities with a different geometry

---

.github/workflows/tests.yml
setup.cfg

- Adds Python 3.10, 3.11 (most recent versions) to tests
- Removes support for python 3.6 (it's several months past end-of-life -- https://www.python.org/dev/peps/pep-0440/#compatible-release)
- Updates minimum scipy version (it was only 0.18, the most recent version is 1.9)

Python versions

---

HISTORY.rst
frank/__init__.py
setup.cfg

The `setup` was changed in frank v.1.2.0, moving everything from `setup.py` to `setup.cfg`. The syntax is slightly different, and it resulted in the non-python files (the `.json` files and the matplotlib style file) in the `frank` source dir not being included in the pip release (even though they're specified in the `MANIFEST`). This is subtle; `python setup.py sdist` shows these files included in the distribution, but they're not copied into the frank source dir when the package is pip installed. I fixed this and suggest this PR update the code to v1.2.1 so I can issue a new pypi release.

Include non-py files in install

---

.github/workflows/docs.yml
.github/workflows/tests.yml
setup.cfg

Github has made a couple of changes to actions that has resulted in errors for frank:
1. Removing support for python3.6
2. Removing support for node.js 12, used by some actions within the frank process.
I've fixed these by 1. removing python3.6 from the tests and 2. updating to newer versions of the actions. The tests are now passing.

Fix for github actions update

---

frank/fit.py
frank/make_figs.py

The functions in `make_figs` are...blah. This PR makes one small change that saves annoyance, deleting the unneeded `priors` arg in a couple figures.

Simplify fig functions

---

frank/io.py
frank/statistical_models.py
frank/tests.py
setup.cfg

I ran into an issue saving/loading a sol object from a debris fit -- `pickle` was struggling to interpret `sol._vis_map._scale_height` as a function:
saving: `AttributeError: Can't pickle local object '<some function for H(R)>'`
loading: `OSError: Failed to interpret file '<some path>_frank_sol.obj' as a pickle`
Replacing `pickle` with `dill` resolves this. PR changes:
- `io.py`: Updates `pickle` calls to `dill`
- `tests.py`: Adds test for save/load of a sol from a standard and debris fit

Update `sol` save/load; add test

---

frank/io.py

Ensures that `io.save_fit` stores the correct brightness profile uncertainty regardless of whether the fit method is `Normal` or `LogNormal`.
Fixes #206

save_fit: save correct profile uncertainty

---

frank/default_parameters.json
frank/fit.py
frank/parameter_descriptions.json
frank/statistical_models.py

Adds functionality for running fits with scale height inference from the terminal.

Debris interfacing

---

frank/utilities.py

Calling `utilities.sweep_profile` with `project=False` and `phase_shift=True` raises an error because `dra` and `ddec` are defined internally only if `phase_shift = True`. PR fixes this.

Bug in sweep_profile args

---

frank/utilities.py

`atleast_1d` call signature has changed in recent numpy versions (confirmed on v1.21.5; current version is 1.26.1). PR updates call signature to not rasie error in `utilities.normalize_uv`
Fixes #210

Update atleast_1d syntax for new numpy versions

---

frank/tests.py
frank/utilities.py

Adds tests for the routines in `utilities.py` that aren't covered by existing tests. These tests check that the routines simply run and that they give the expected numerical results.
Closes #214

Utils tests

---

setup.cfg

This PR tries to fix #222 by excluding the broken scipy versions.

Fix scipy nnls issue

---

frank/fit.py
frank/utilities.py

People often pass in _u_ and _v_ coordinates in [m], then either the fit fails or they get confused by the fit results. This PR:
- adds a function to check the units and issue a warning if they appear to be in [m] rather than the expected [lambda]. 
- adds the check to the pipeline in `fit.py`

Add sanity check of (u,v) units

---

frank/utilities.py

Adds arg to `get_fit_stat_uncer` to return linear or log uncertainty for a LogNormal fit.
closes #220

Add scaling option for return of get_fit_stat_uncer

---

frank/geometry.py

I spotted a typo when doing `print(geometry)`. This PR makes it so that the output can be simply copied to create a FixedGeometry object, which is useful, e.g., when fitting the geometry once.

Fixed typo in geometry printing
