discsim/frank

- frankenstein/geometry.py
- frankenstein/radial_fitters.py
- frankenstein/tests.py
Here is a suggested implementation of the new interface for the geometry fit. Let me know what you think. The interface is now more consistent with the fitters interface. To see how it all works, look at the new tests. 
It still needs docs and cleaning up - e.g. I will remove / hide the fit_geometry_gaussian function.
> Changing geometry to object-orientated interface [do not merge]

- frankenstein/__init__.py
- frankenstein/constants.py
- frankenstein/fit.py
- frankenstein/geometry.py
- frankenstein/hankel.py
- frankenstein/io.py
- frankenstein/radial_fitters.py
- frankenstein/tests.py
> Added GPL message

- .circleci/config.yml
- requirements.txt
- setup.py
> Removed non-critical dependencies from requirements

- docs/py_API.rst
- frankenstein/geometry.py
- frankenstein/radial_fitters.py
I've filled in the page that documents the API of the main methods.
> Added python api docs

- .gitignore
- frank/default_parameters.json
- frank/fit.py
- frank/geometry.py
- frank/parameter_descriptions.json
- frank/radial_fitters.py
- frank/utilities.py
I have changed how the geometry fit is specified in fit.py. The motivation for this change is to make it impossible to accidentality specify multiple options, which was possible before. Now the user will be 100% certain what kind of fit they will get.
> Changed how geometry is specified

- frank/utilities.py
> Fixed warning in UV binning

- frank/default_parameters.json
- frank/fit.py
- frank/io.py
- frank/parameter_descriptions.json
This pull request implements multiple output formats for the frank fit. 
We should wait for #55 before proceeding here.
> Added variable output types

- README.md
In case anyone comes across the repo before the code's release
> Update temporary README.md

- frank/fit.py
Fixed a bug that I did not notice in the original boot-strap PR
> [Urgent] fixed bootstrap code

- frank/default_parameters.json
- frank/fit.py
- frank/parameter_descriptions.json
- frank/radial_fitters.py
I've added the option to produce non-negative fits. 
The code proceeds as normal, but right at the end I am finding the best-fit non-negative brightness given the MAP power spectrum. I've added an option to the bootstrap to use this instead of the mean, if desired.
> Fits with non-negative brightness

- README.md
- frank/default_parameters.json
This PR quickly updates the README to be more direct that the code is still under construction (pre-v1.0). I ask that this be merged into master now so that those who find the repo understand the code isn't fully public yet.
> URGENT: pre-release README warning

- frank/fit.py
I've added a simple hack to take care of #78. It only works when using frank as a library
Is this too bad? There aren't many other options, apart from https://github.com/joblib/threadpoolctl
> disabled threading in numpy/scipy

- frank/fit.py
- frank/utilities.py
This updates the way the weights are determined as discussed in #98. 
I had to make some cosmetic changes to UVDataBinner to get this to work, plus a small bug-fix.
I also decided against doing something too sophisticated, since its probably difficult to make something sufficiently general.
Once you're happy with this, I'll delete the old code
> Added new weight estimation facility

- frank/radial_fitters.py
> Raise exception on bad powerspectrum value

- frank/geometry.py
- frank/tests.py
> Corrected phase centre shift signs

- .circleci/config.yml
This begins a set of tests on circle ci checking the code against different python versions (3.x).
> Matrix of tests on Circle CI

- frank/utilities.py
This PR fixes a bug I spotted in utiltities.py
> Bug fix - estimate weights

- README.md
- docs/index.rst
This PR is to enable Jeff to push the final change - the arxiv link - needed for the PyPI version 1.0 release
> Arxiv link, final changes for version 1.0

- README.md
- docs/index.rst
Adds the link to the repo README and the docs' index
Fixes #42
> Add ADS frank methods paper link

- frank/utilities.py
This PR fixes a bug in convolve_profile
> Correct cos_i bug in convolve_profile

- frank/utilities.py
This PR just adds a logging message to utilities.normalize_uv.
> Add logging message to utilities.normalize_uv

- docs/tutorials.rst
the video tutorial already has 8 views! #viral
> Add docs link to first video tutorial

- frank/fit.py
> Noticed a small typo in docstring

- frank/fit.py
This just changes 2 logging statements in `fit.py` to only print if conditions are met (if anything in the fit is saved, or any figure is made), to avoid confusion when running from terminal. Nothing besides these 2 checks is changed.
> clean up logging statements

- frank/fit.py
- frank/make_figs.py
- frank/plot.py
First changes to improve `plot.py` and `make_figs.py`. All tests are passing on this branch.
Fixes #171
> Fix plot errors/warnings

- frank/utilities.py
Generalizes `utilities/normalize_uv` to handle pointwise wavelengths
> normalize_uv generalization 

- frank/filter.py
- frank/geometry.py
- frank/minimizer.py
- frank/radial_fitters.py
- frank/statistical_models.py
Fixes a couple typos in docstrings and adds a few parameters into them that are missing
> Docstrings

- frank/hankel.py
- frank/utilities.py
Adds routines to generate mock visibilities and to add Gaussian noise to visibilities
> Mock data routines

- frank/default_parameters.json
- frank/fit.py
- frank/make_figs.py
- frank/parameter_descriptions.json
- frank/tests.py
- Makes `nonnegative` param in .json true by default (as this just calls `setattr(sol, '_nonneg', sol.solve_non_negative())` in `fit.py`)
* adds check in `fit.py` for whether the fit method is also `Normal`
- Adds `sol.solve_non_negative` to quick and full figures      
*  cleans up some general plot settings, figure syntax
- Adds test for `sol.solve_non_negative`
> Add non-negative solution to figs; add non-neg. test

- frank/make_figs.py
- frank/plot.py
- frank/radial_fitters.py
- frank/utilities.py
- Adds a function to `utilities` that calculates statistical uncertainty of a fitted I(r). 
- Adds the `method` key to the `_info` property of `FrankFitter`
> Statistical uncertainty recovery function

- frank/default_parameters.json
- frank/fit.py
- frank/parameter_descriptions.json
- frank/radial_fitters.py
This PR has been introduced to fix #202. The options still need adding to fit.py and the parameter file
> Raise error on convergence failure

- frank/debris_fitters.py
- frank/filter.py
- frank/hankel.py
- frank/radial_fitters.py
- frank/statistical_models.py
This contains the code needed to update the debris disc fitter routines to the versions in the published paper. There are a few other changes in this branch unfortunately, but they are cosmetic or additional minor features, e.g. adding direct interpolation formulae to the Hankel transform.
> Debris disc fitter, paper version

- frank/statistical_models.py
Generalize message so as to be more helpful.
closes #218 
Tests will fail until #222 is addressed.
> `GaussianModel`: update failed fit error message

- .github/workflows/docs.yml
> updated upload-artifact
